[SPPP-625]: test

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,3 +2,12 @@
 . "$(dirname "$0")/_/husky.sh"
 
 dotnet format
+
+dotnet build --configuration Release
+
+if [ $? -ne 0 ]; then
+  echo "Compile failed. No confirmations allowed."
+  exit 1
+fi
+
+exit 0
